projectPiki/pikmin2

README.MD
include/Dolphin/rand.h
include/Dolphin/trk.h
include/Game/Cave/Node.h
include/Game/Cave/RandMapMgr.h
include/Game/Cave/RandMapUnit.h
obj_files.mk
src/Dolphin/e_asin.c
src/Dolphin/e_atan2.c
src/Dolphin/e_exp.c
src/Dolphin/e_fmod.c
src/Dolphin/e_log.c
src/Dolphin/e_log10.c
src/Dolphin/e_pow.c
src/Dolphin/e_rem_pio2.c
src/Dolphin/e_sqrt.c
src/Dolphin/k_cos.c
src/Dolphin/k_rem_pio2.c
src/Dolphin/k_sin.c
src/Dolphin/s_atan.c
src/Dolphin/s_ceil.c
src/Dolphin/s_copysign.c
src/Dolphin/s_cos.c
src/Dolphin/s_floor.c
src/Dolphin/s_frexp.c
src/Dolphin/s_modf.c
src/Dolphin/s_sin.c
src/Dolphin/s_tan.c
src/plugProjectNishimuraU/RandCapEnemyUnit.cpp
src/plugProjectNishimuraU/RandMapDraw.cpp

matched + linked (+ commented), updated Game::Cave::MapUnitGenerator struct (_2C >> m_visitedMapNodes) in Game/Cave/RandMapUnit.h header as well - also includes progress from RandCapEnemyUnit.cpp

RandMapDraw.cpp

---

README.MD
include/Game/Cave/Node.h
include/Game/Cave/ObjectLayout.h
include/Game/Cave/RandMapMgr.h
obj_files.mk
src/plugProjectNishimuraU/RandMapDraw.cpp
src/plugProjectNishimuraU/RandPlantUnit.cpp

Matched/linked/commented, updated some headers (RandPlantUnit in Game/Cave/RandMapMgr.h, UnitInfo in Game/Cave/ObjectLayout.h), plus some formatting

RandPlantUnit.cpp

---

README.MD
include/JSystem/JGadget/binary.h
include/JSystem/JGadget/linklist.h
include/JSystem/JMessage.h
include/JSystem/JMessage/TControl.h
include/JSystem/JMessage/TParse.h
include/JSystem/JMessage/TProcessor.h
include/JSystem/JMessage/TReference.h
include/JSystem/JMessage/TResource.h
include/P2JME/Analyzer.h
include/P2JME/TReference.h
include/P2JME/TRenderingProcessor.h
obj_files.mk
src/JSystem/binary.cpp
src/JSystem/control.cpp
src/JSystem/linklist.cpp
src/JSystem/processor.cpp
src/JSystem/resource.cpp

good chunk of JSystem header progress (TProcessor/TResource/TControl) along with another sysGCU file

link messageAnalyzer.cpp and fix JSystem headers

---

README.MD
include/JSystem/JMessage/TProcessor.h
include/P2JME/TSequenceProcessor.h
obj_files.mk
src/sysGCU/messageSequence.cpp
tools/progress.csv

also fixed P2JME/TSequenceProcessor.h header - variables need renaming to intelligible things eventually + documenting, but really unsure what anything does at this stage without more files done
(thanks to SwareJonge for the help with a couple switch statements!)

messageSequence.cpp matched and linked

---

README.MD
asm/plugProjectEbisawaU/ebiP2TitleFog.s
include/Color4.h
include/Dolphin/gx.h
src/plugProjectEbisawaU/ebiP2TitleFog.cpp
src/sysGCU/fogMgr.cpp

also correct GXSetFog parameters

refactor fogMgr code and related types

---

include/nans.h

Fixed the underscores of nans.h to align with map

Add underscores to nans

---

src/plugProjectNishimuraU/RandMapDraw.cpp

namespacing had issues. is fixed.

Fix RandMapDraw.cpp namespacing

---

include/Game/pelletMgr.h
src/plugProjectKandoU/onyonMgr.cpp
src/plugProjectKandoU/pelletMgr.cpp
src/plugProjectKandoU/vsGameSection.cpp

Might be helpful for pelletMgr.cpp, also GitHub is dumb and made some files incorrectly utf-8 so that needs to be fixed

 _32C -> m_pelletFlag, PelletFlag enum 

---

Makefile

Properly handle sha1sum/shasum OS differences

---

include/Vector2.h
include/ebi/E3DGraph.h
include/ebi/title/Entities/TKogane.h
include/ebi/title/TTitle.h
src/plugProjectEbisawaU/ebiP2Title.cpp
src/plugProjectEbisawaU/ebiP2TitleChappy.cpp
src/plugProjectEbisawaU/ebiP2TitleKogane.cpp

Started work mostly on the ebiP2TitleKogane.cpp and TKogane.h files

ebiP2TitleKogane

---

include/Game/BaseGameSection.h
include/Game/GameSystem.h
include/Game/MoviePlayer.h
include/Game/gameGenerator.h
include/PSSystem/PSGame.h
include/ParticleMgr.h
include/Rect.h
include/Splitter.h
include/Sys/DrawBuffers.h
include/SysShape/Model.h
include/Vector2.h
include/Viewport.h
src/plugProjectKandoU/baseGameSection.cpp
src/plugProjectKandoU/onyonMgr.cpp
src/sysGCU/demoSection.cpp
src/sysGCU/sysDrawBuffer.cpp

BaseGameSection progress

---

docs/recommended_todo.md
include/Game/Entities/UmiMushi.h
include/Matrixf.h
include/PSM/CreatureAnime.h
include/Vector3.h
src/plugProjectMorimuraU/umiMushi.cpp

Yeah there's two of them... sorry

UmiMushi progress

---

asm/Dolphin/TRK_MINNOW_DOLPHIN/__exception.s

Use __exception.s from Wii Sports decomp

---

include/Game/Entities/ItemBridge.h
src/plugProjectKandoU/itemBridge.cpp

itemBridge.cpp:
Matched function "getBridgeZVec()"
Matched function "getBridgeXVec()"
Fixed function "onInit()"

Matched functions in plugProjectKandoU/itemBridge.cpp

---

include/Game/Entities/Armor.h
src/plugProjectKandoU/itemBridge.cpp
src/plugProjectNishimuraU/Armor.cpp

Decompiled function "void killSlotPiki()" in Armor.cpp
Changed function signature from "void getSlotPikiNum()" to "int getSlotPikiNum()" in Armor.h
Decompiled function "int getSlotPikiNum()" in Armor.cpp

Decompiled functions in plugProjectNishimuraU/Armor.cpp

---

include/Game/MemoryCard/Mgr.h
include/MemoryCardMgr.h
include/ebi/Save.h
include/ebi/Screen/TSaveMenu.h
src/plugProjectEbisawaU/ebiSaveMgr.cpp

There's some inheritance dtor shenanigans going on that I've got no fucking clue how to solve, though

Solved that one function

---

src/plugProjectNishimuraU/Ujia.cpp

Matching resetAppearCheck and setNearestBridge

Ujia progress

---

configure.py

Specifies target/base paths only if they're included in the build process (aka asm/c files exist).
Sets the "complete" field for color coding.

Adjust configure.py for new objdiff

---

include/MemoryCardMgr.h
src/sysGCU/memoryCard.cpp
src/sysGCU/pikmin2MemoryCardMgr.cpp

More function scaffolding and cleanup in memoryCard.cpp and pikmin2MemoryCardMgr.cpp cause I got nostalgic.

Memory Card improvements

---

include/Game/BaseHIO.h
include/RootMenuSection.h
include/Section.h
src/sysGCU/section.cpp

I ran into problems with inlining when trying to match Section::run(). Its pretty close otherwise.

Improve section.cpp for USA Demo 1

---

include/Game/Entities/PanModokiBase.h
src/plugProjectMorimuraU/panModoki.cpp

Overall, 18 functions that still aren't matching, 6 of them currently below 50%. 1 function went from matching to not matching due to inlining.

Finish scaffolding panModoki.cpp

---

.vscode/c_cpp_properties.json
.vscode/extensions.json

- Updated `c_cpp_properties.json` to account for other platforms.
- Added `ms-vscode.makefile-tools` to recommended extensions.

Tweaks to VS Code settings

---

include/sqrt.h
src/Dolphin/thp/THPDec.c
src/plugProjectKandoU/cellPyramid.cpp
src/sysCommonU/sysMath.cpp

This should be the last of 'em

Missed a few asms

---

Makefile
configure.py
tools/download_ppc.py

Rename dkp files if they lack the prefix instead

---

docs/recommended_todo.md
include/P2JME/Movie.h
src/sysGCU/movieMessage.cpp

Improved setMode to 60%.
That's the most I can manage right now with this file, you're welcome to add commits to this branch to clean things up or add more improvements.

Improve movieMessage.cpp

---

src/plugProjectKandoU/baseGameSection.cpp

guys just day >= 30 it's not that hard

initGenerators down to regswaps

---

include/ParticleMgr.h
include/PikiAI.h
src/plugProjectKandoU/baseGameSection.cpp

more basegamesection work

---

include/Game/pathfinder.h
include/Game/routeMgr.h
src/plugProjectKandoU/aiPrimitives.cpp
src/plugProjectKandoU/pathfinder.cpp
src/plugProjectKandoU/routeMgr.cpp
src/plugProjectMorimuraU/blackMan.cpp
src/plugProjectMorimuraU/panModoki.cpp

guys did no one merge this?? smh

Cleanup pathfinding chicanery

---

src/plugProjectMorimuraU/panModoki.cpp

MERGE IT PLEASE IT'S LITERALLY ONE LINE OF CODE I BEG YOU TO MERGE IT

One line change moment

---

include/JSystem/JUtility/TColor.h
include/P2JME/messageObj.h
src/sysGCU/windowMessage.cpp

I'm open to suggestions for the name of the new function I created for `messageObj.h` It really does seem to use a different version of getCalc for some reason based on the order of operations.

Improve windowMessage.cpp

---

include/P2JME/messageRendering.h
include/stl/ctype.h
src/JSystem/JMessage/processor.cpp
src/sysGCU/messageRendering.cpp

I tried to improve these files until they got to equivalency, but I got stuck on an odd problem where our current attempt inverts the font graphics for no apparent reason.

Improve messageRendering.cpp and processor.cpp

---

src/JSystem/JAudio/JAS/JASTrack.cpp
src/JSystem/JAudio/JAS/JASTrackInterrupt.cpp

Port some more intel about JAudio from Pikmin 1.
